name: Daily Billing Alert

on:
  schedule:
    # Run daily at 9 AM UTC
    - cron: '0 9 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  check-billing:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Check OpenAI billing usage
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
          ALERT_EMAIL: ${{ secrets.ALERT_EMAIL }}
        run: |
          # Make a POST request to the billing alert endpoint
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "x-cron-secret: $CRON_SECRET" \
            -d '{}' \
            https://your-domain.com/api/billing-alert
            
      - name: Send notification on failure
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          channel: '#alerts'
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}